print("\033[1;32m",end='')
print('██████')
print('██████')
print('██████')
print(' ')
print(' ')
                
print("\033[1;31m",end='')
print('██████')
print('██████')
print('██████')
print(' ')
print(' ')
               
print('\033[0;33m',end='')
print('██████')
print('██████')
print('██████')
print(' ')
print(' ')
                
print("\033[0;30m",end='')
print('██████')
print('██████')
print('██████')
print(' ')
print(' ')
             
print("\033[0;37m",end='')
print('██████')
print('██████')
print('██████')
print(' ')
print(' ')

print("\033[1;33m",end='')
print('██████')
print('██████')
print('██████')
print(' ')
print(' ')